M48
; DRILL file {KiCad (7.0.0-0)} date Monday, February 27, 2023 at 11:59:41 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-27T23:59:41-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X144.78Y-97.21
T2
X112.522Y-91.821
X147.32Y-111.76
T0
M30
